version: '3'

services:
    nginx:
        image: nginx:stable
        ports:
            - "80:80"
        volumes:
            # app dir
            - ../app:/var/www/html/app
            - ./server-config/nginx:/etc/nginx/conf.d/
            - ./data/logs/nginx/:/var/log/nginx
        links:
            - php
        networks:
            net:
                # sharing hosts for all services
                aliases:
                    - ${DOMAIN}
    php:
        build: docker/images/php-fpm-7.4
        user: "dev"
        expose:
            - "9000"
        volumes:
            # app dir
            - ../app:/var/www/html/app
            - ./data/composer:/home/dev/composer
            - ./server-config/php/dev.ini:/usr/local/etc/php/php.ini
        links:
            - postgres
            - redis
        environment:
            - DOMAIN=${DOMAIN}
        networks:
            - net
    postgres:
        image: postgres:11
        ports:
            - "5432:5432"
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=${COMPOSE_PROJECT_NAME}
            - POSTGRES_PASSWORD=123
        volumes:
            - ./data/logs/pgsql/:/var/log/pgsql
            - pgsql-data:/var/lib/pgsql
        networks:
            - net
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - net
volumes:
    pgsql-data:

networks:
    net:
        driver: bridge
